# GitHub Pages configuration
baseurl: "/inheekwak.github.io"   # empty if using inheekwak.github.io as the repository name
url: "https://inheekwak.github.io"

# Site information
title: "Inhee Kwak"
description: "My name is Inhee Kwak and I am a researcher"

# Theme
theme-color: indigo

# Homepage information
author: Inhee Kwak
author-bio: "Psychology + Computer"
author-image: master_grad_pic.jpeg

# Navigation menu
show-nav-menu: true

nav-menu:
  - text: About
    permalink: about
  - text: CV
    permalink: cv
  - text: Publication
    permalink: publication

# Social media
twitter: https://twitter.com/inheekwak
instagram: https://instagram.com/inheeisinhere
github: https://github.com/inheekwak
linkedin: https://www.linkedin.com/in/inheekwak
medium: false
google-scholar: false
email: inhee@applied-computing.org

# Analytics
google-analytics: G-WCRC1TC2V5

# Plugins
plugins:
  - jekyll-seo-tag
