# Basic Information 
title: Inhee Kwak
position: Researcher
affiliation: TBD
affiliation_link: TBD
#affiliation_logo: ./assets/img/human brain icon.png
email: 1nh33kwak (at) gmail.com

# Search Engine Optimization (SEO)
keywords: inhee kwak, kwak inhee, inheekwak, kwakinhee
#canonical: https://yaoyaoliu.web.illinois.edu
description: Inhee Kwak is a researcher focusing on the application of AI within the mental health field. Their research lies in digital phenotyping, multi-modal modeling for mental illness, and affective computing.

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
#google_scholar: https://scholar.google.com/citations?user=Qi2PSmEAAAAJ
github_link: https://github.com/inheekwak/
linkedin: https://www.linkedin.com/in/inheekwak/
twitter: https://twitter.com/inheekwak/

# Images 
avatar: ./assets/img/profile_pic.jpeg

# Footnotes
footnote: Feel free to contact me.
footnote_link: 1nh33kwak@gmail.com

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
