# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://inheekwak.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Inhee Kwak"
description: My name is Inhee Kwak and I am a researcher

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Inhee Kwak
author-bio: Psychology + Computer
author-image: master_grad_pic.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: CV
  permalink: cv
- text: Publication
  permalink: publication

# use false to turn off any social media links
twitter: https://twitter.com/inheekwak
instagram: https://instagram.com/inheeisinhere
github: https://github.com/inheekwak
linkedin: https://www.linkedin.com/in/inheekwak
medium: false
google-scholar: false
email: inheek@upenn.edu

# footer information
# footer-msg: "Powered by Tailpages"
# footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
